config/routes.rb
Rails.application.routes.draw do
  resources :sales, only: %i[index new create]
  root 'sales#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
# frozen_string_literal
class Sale < ApplicationRecord
	# br_dinheiro
	usar_como_dinheiro :unit_price
	# Pagination
	paginates_per 20
	# Validations
  validates :buyer, :description, :unit_price, :quantity,
            :supplier, :address, presence: true

  validates_numericality_of :unit_price, :quantity
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sales_controller.rb
# frozen_string_literal
class SalesController < ApplicationController
  def index
    @sales = Sale.order(created_at: 'DESC').page(params[:page])
  end

  def new
    @import = Services::UploadFile.new
  end

  def create
    @import = Services::UploadFile.new(sale_params)
    if @import.valid?
      @import.save
      respond_to do |format|
        format.html { redirect_to root_path, notice: t('flash.sales.create.notice') }
      end
    end
  end

  private

  def sale_params
    params.require(:services_upload_file).permit(:file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def last_sales
    Sale.order(created_at: 'DESC').limit(5)
  end

  def to_br(date)
  	date.strftime('%d/%m/%Y')
  end

  def total
  	@total ||= Sale.all.inject(0) { |tot, i| tot += (i.unit_price * i.quantity) }
  end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/application/_side_nav.html.erb
<ul id="slide-out" class="side-nav fixed">
  <li>
    <div class="user-view">
      <div class="background">
        <%= image_tag 'img1' %>
      </div>
      <%= image_tag 'img2', class: 'circle' %> 
      <a href="#!name"><span class="white-text name">Seja bem vindo!</span></a>
      <a href="#!email"><span class="white-text email"><%= to_br(Date.current) %></span></a>
    </div>
  </li>

  <li><%= link_to t('menu.new_sale'), new_sale_path %></li>
  <li><%= link_to "#{t('menu.total')}: #{total}", root_path %></li>
  <li><div class="divider"></div></li>
  <% last_sales.each do |d| %>
    <li><a href="#"><%= to_br(d.created_at) %></a></li>
  <% end %>
  <li><div class="divider"></div></li>
  <li><a href="#" class="purple-text text-darken-3"> <%= t('menu.footer', year: Date.current.strftime('%Y')) %></a></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleBox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <header>
        <%= render 'side_nav' %>
      </header>
      <main>
        <%= yield %>
      </main>
      <footer>
      </footer>
    </div>
  </body>
</html>

app/views/sales/_form.html.erb
<%= form_for(import, url: sales_path, html: { multipart: true }) do |f| %>
  
  <%= f.file_field :file, class: 'more-bottom', required: true %>
  <br />
  <div class="actions">
    <button  class="btn waves-effect waves-light" type="submit" name="action">
      Enviar arquivo <i class="material-icons right">send</i>
    </button>
  </div>
<% end %>

app/views/sales/_sales.html.erb
<table class="striped">
  <thead>
    <tr>
      <th><%= t('titles.sale.index.buyer') %></th>
      <th><%= t('titles.sale.index.description') %></th>
      <th><%= t('titles.sale.index.unit_price') %></th>
      <th><%= t('titles.sale.index.quantity') %></th>
      <th><%= t('titles.sale.index.supplier') %></th>
      <th><%= t('titles.sale.index.address') %></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
    <tr>
      <td><%= sale.buyer %></td>
      <td><%= sale.description %></td>
      <td><%= sale.unit_price %></td>
      <td><%= sale.quantity %></td>
      <td><%= sale.supplier %></td>
      <td><%= sale.address %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/sales/index.html.erb
<p class="flow-text center-align">
  <%= t('titles.sale.index.title') %>
</p>
<p class="right-align">
  <%= link_to new_sale_path do %>
    <i class="material-icons purple-text text-darken-3 right">add</i><%= t('actions.new') %>
  <% end %>
</p>
<div class="col s12 m6">
  <div class="card-panel">
    <div id="sales">
      <%= render 'sales', sales: @sales %>
    </div>
  </div>
</div>

<div id="paginator">
  <%= paginate @sales, remote: true %>
</div>

app/views/sales/index.js.erb
$('#paginator').html('<%= j(paginate @sales, remote: true) %>');
$("#sales").html("<%= j render 'sales', sales: @sales %>");

app/views/sales/new.html.erb
<div class="card more-top">
  <div class="card-content">
  	<div class="more-bottom">
	    <p class="flow-text"><%= t('titles.sale.new.title') %></p>
  	</div>
		<%= render 'form', import: @import %>
	</div>
</div>